defaults:
  target_tokens: 800
  overlap_tokens: 80

by_doc_type:
  press_release: {mode: "single"}
  speaking_tracker: {mode: "header_sections"}
  bio_profile: {mode: "single"}
  press_statement: {mode: "single"}
  pitch_email: {mode: "single"}
  media_response: {mode: "single"}
  messaging_one_pager: {mode: "header_sections"}
  messaging_notes|style_guide: {mode: "header_sections"}
  talking_points: {mode: "header_sections"}
  interview_guide: {mode: "header_sections"}
  interview_question_bank: {mode: "header_sections"}
  outreach_template: {mode: "single"}
  competitive_analysis: {mode: "header_sections"}
  annual_report: {mode: "header_sections"}
  report_results: {mode: "header_sections"}
  web_copy: {mode: "header_sections"}
  work_plan|strategy_memo: {mode: "header_sections"}
  deck|analysis_report: {mode: "slides"}
  deck|training_materials: {mode: "slides"}
  story_bank: {mode: "summary_only"}
  media_list: {mode: "summary_only"}
  editorial_calendar: {mode: "header_sections"}
  coverage_tracker: {mode: "header_sections"}
  partnership_blurb: {mode: "single"}
  conference_proposal: {mode: "header_sections"}
  timeline: {mode: "header_sections"}
  workback_plan: {mode: "header_sections"}
  event_qna: {mode: "single"}
  op_ed_draft: {mode: "header_sections"}
  fact_sheet: {mode: "header_sections"}
  proclamation_language: {mode: "single"}
