required_columns:
  - doc_id
  - campaign_id
  - doc_type
  - title
  - date
  - language
  - index_mode
  - pii_flags
  - canonical
  - source_path

enums:
  index_mode: [full, summary_only, redacted]
  confidentiality_level: [Low, Med, High]
  doc_type:
    - bio_profile
    - press_release
    - press_statement
    - pitch_email
    - media_response
    - messaging_one_pager
    - messaging_notes|style_guide
    - talking_points
    - interview_guide
    - interview_question_bank
    - outreach_template
    - competitive_analysis
    - annual_report
    - report_results
    - web_copy
    - work_plan|strategy_memo
    - deck|analysis_report
    - deck|training_materials
    - story_bank
    - speaker_tracker
    - media_list
    - editorial_calendar
    - coverage_tracker
    - partnership_blurb
    - conference_proposal
    - timeline
    - workback_plan
    - event_qna
    - op_ed_draft
    - fact_sheet
    - proclamation_language
