labels:
  - press_release
  - bio_profile
  - speaking_tracker
  - platform_copy_edits
  - press_statement
  - pitch_email
  - media_response
  - messaging_one_pager
  - messaging_notes|style_guide
  - talking_points
  - interview_guide
  - interview_question_bank
  - outreach_template
  - competitive_analysis
  - annual_report
  - report_results
  - web_copy
  - work_plan|strategy_memo
  - deck|analysis_report
  - deck|training_materials
  - story_bank
  - media_list
  - editorial_calendar
  - coverage_tracker
  - partnership_blurb
  - conference_proposal
  - timeline
  - workback_plan
  - event_qna
  - op_ed_draft
  - fact_sheet
  - proclamation_language

synonyms:
  press_release: ["press release","news release","for immediate release","media contact"]
  bio_profile: ["bio","biography","speaker bio","panelist bio","headshot","about the speaker"]
  speaking_tracker: ["speaking opportunities","conference tracker","cfp tracker","call for speakers","speaker opportunities"]
  press_statement: ["press statement","statement from","we applaud","we condemn"]
  pitch_email: ["pitch","media pitch","initial pitch","follow-up pitch","lat 404 pitch","reaching out","following up","subject:"]
  media_response: ["response to","we appreciate the inquiry","for accuracy"]
  messaging_one_pager: ["one-pager","overview","summary"]
  messaging_notes|style_guide: ["messaging dump","notes","style guide","voice"]
  talking_points: ["talking points","tps","key messages","interview prep"]
  interview_guide: ["interview guide","stakeholder interview","question set"]
  interview_question_bank: ["general questions","role-specific","moment you realized"]
  outreach_template: ["outreach","scheduling","availability","interested in speaking"]
  competitive_analysis: ["peer organizations","peer orgs","peer list","peer matrix","competitor matrix","competitors","rubric"]
  annual_report: ["annual report"]
  report_results: ["briefing","activation","results"]
  web_copy: ["webpage","site copy","landing page","program explainer"]
  work_plan|strategy_memo: ["work plan","deliverables","timeline","milestones","owners"]
  deck|analysis_report: ["slide","deck","analysis slides","network map","sentiment","media analysis"]
  deck|training_materials: ["media training","training deck"]
  story_bank: ["story bank","stories of impact"]
  media_list: ["media list","press list","reporters","outlets","beat"]
  editorial_calendar: ["editorial calendar","content calendar"]
  coverage_tracker: ["coverage tracker","coverage"]
  partnership_blurb: ["overview blurb","partnership"]
  conference_proposal: ["learning objectives","session proposal","conference application"]
  timeline: ["timeline"]
  workback_plan: ["work back plan","workback","project workback","reverse timeline"]
  event_qna: ["event questions","q&a"]
  op_ed_draft: ["op-ed","op ed","opinion","byline"]
  fact_sheet: ["fact sheet","factsheet","quick facts"]
  proclamation_language: ["proclamation","proclamation language"]
